languages:
  Ruby: true
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/NumericLiterals:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "app/assets/**/*"
